// flow-typed signature: ec18737ca1c3a9fb808652ff2ebdfa7b
// flow-typed version: <<STUB>>/vite-plugin-run_v^0.5.1/flow_v0.228.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite-plugin-run'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite-plugin-run' {
  declare module.exports: any;
}
