// flow-typed signature: e9c3bef4ab7138ba127d11a3467324cc
// flow-typed version: <<STUB>>/vite_v^5.0.8/flow_v0.228.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vite/bin/vite' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep---u6OAyB' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-8a-6Quh6' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-9A4-l-43' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-FrUgnvs5' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-kjUoH5nk' {
  declare module.exports: any;
}

declare module 'vite/dist/node/cli' {
  declare module.exports: any;
}

declare module 'vite/dist/node/constants' {
  declare module.exports: any;
}

declare module 'vite/dist/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vite/bin/vite.js' {
  declare module.exports: $Exports<'vite/bin/vite'>;
}
declare module 'vite/dist/node/chunks/dep---u6OAyB.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep---u6OAyB'>;
}
declare module 'vite/dist/node/chunks/dep-8a-6Quh6.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-8a-6Quh6'>;
}
declare module 'vite/dist/node/chunks/dep-9A4-l-43.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-9A4-l-43'>;
}
declare module 'vite/dist/node/chunks/dep-FrUgnvs5.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-FrUgnvs5'>;
}
declare module 'vite/dist/node/chunks/dep-kjUoH5nk.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-kjUoH5nk'>;
}
declare module 'vite/dist/node/cli.js' {
  declare module.exports: $Exports<'vite/dist/node/cli'>;
}
declare module 'vite/dist/node/constants.js' {
  declare module.exports: $Exports<'vite/dist/node/constants'>;
}
declare module 'vite/dist/node/index' {
  declare module.exports: $Exports<'vite/dist/node'>;
}
declare module 'vite/dist/node/index.js' {
  declare module.exports: $Exports<'vite/dist/node'>;
}
