// flow-typed signature: 53053cbd44a9ef5580c43903246d9963
// flow-typed version: <<STUB>>/vite-plugin-babel_v^1.2.0/flow_v0.228.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite-plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite-plugin-babel' {
  declare module.exports: any;
}
